# Generated by Django 2.2.4 on 2019-12-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.TextField(max_length=16, verbose_name='密码')),
                ('avatar', models.TextField(max_length=32, verbose_name='头像')),
                ('nick', models.TextField(max_length=8, verbose_name='昵称')),
            ],
        ),
    ]
