# Generated by Django 2.2.4 on 2020-01-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.CreateModel(
            name='VoiceAssistantKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16, verbose_name='关键字名称')),
                ('key_word', models.TextField(max_length=128, verbose_name='关键字列表，以逗号为间隔')),
                ('func_name', models.TextField(default='null', max_length=32, verbose_name='执行的方法名')),
                ('code', models.TextField(default='null', max_length=256, verbose_name='要执行的代码')),
                ('users', models.ManyToManyField(to='userManage.User')),
            ],
        ),
    ]
