# Generated by Django 2.2.4 on 2020-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0002_auto_20200119_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=32, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=8, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='voiceassistantkeyword',
            name='code',
            field=models.TextField(default='null', verbose_name='要执行的代码'),
        ),
        migrations.AlterField(
            model_name='voiceassistantkeyword',
            name='func_name',
            field=models.CharField(default='null', max_length=32, verbose_name='执行的方法名'),
        ),
        migrations.AlterField(
            model_name='voiceassistantkeyword',
            name='key_word',
            field=models.CharField(max_length=128, verbose_name='关键字列表，以逗号为间隔'),
        ),
        migrations.AlterField(
            model_name='voiceassistantkeyword',
            name='name',
            field=models.CharField(max_length=16, verbose_name='关键字名称'),
        ),
    ]
