# Generated by Django 2.2.4 on 2020-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0003_auto_20200119_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_words',
            field=models.CharField(default='1,2', max_length=128, verbose_name='当前用户拥有的关键字id，以逗号为间隔'),
        ),
    ]
